### ISSUE TITLE
Simple data accessibility for external users

### ISSUE THREAD

**Issue by adler-j** [tomography/tomobank#3]
As part of the [ODL](https://github.com/odlgroup/odl) package for inverse problems, we have a [submodule](https://github.com/odlgroup/odl/tree/master/odl/contrib/datasets) that provides users with easy access to various publicly available datasets. The datasets in tomobank would be a prime candidate for this, but in order to make the usage as easy as possible it would be preferable if the data was hosted (or if we could host it) directly online, without any signup or similar procedure.

One such option would be zenodo, see e.g. https://zenodo.org/record/800525#.WibVUUpKtPY for an example.

If this was done, we could import the data as such

```python
import odl.contrib.datasets.tomo.tomobank as tomobank
data = tomobank.foo_bar()
```

I'm sure this would increase exposure to your datasets. Is this something you would be interested in supporting?

**Comment by decarlof** [comment]
@adler-j This is a very good suggestion as are also looking into better solutions. The requirement to use gridftp (the transfer protocol running under globus) is because it has demonstrated to be very reliable for transferring full-size large data sets such the one in tomobank.  In earlier discussion, @matze had the same request and I suggested him to explore [globus-sdk-python](https://github.com/globus/globus-sdk-python). Perhaps @matze has an update.

**Comment by adler-j** [comment]
Do you guys have any update on this? We're still very interested!

**Comment by CJ-Wright** [comment]
I would also be interested in this.

**Comment by decarlof** [comment]
I am closing this as [globus-sdk-python](https://github.com/globus/globus-sdk-python) is a solution.
